  version: '3.8'
  services:
    web:
      image: php:8.2-apache
      hostname: web
      ports: 
        - 8010:80
      volumes:
        - ./app:/var/www/html
    mysql:
      image: mysql
      hostname: web
      ports:
        - 3306:3306
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_USER=oscar
        - MYSQL_PASSWORD=oscar
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=alumnos
    phpmyadmin:
      image: phpmyadmin
      ports: 
        - 8011:80
      depends_on:
        - mysql
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
         